// This is a file generated by the yeoman generator hapijs

/**
 * All the endpoints for anything related to <%= name %>
 *
 * @type {exports}
 */
var Joi = require('joi');
var <%= controllerName %> = require('./<%= name %>-ctrl');

module.exports = function() {
  return [
    {
      method: 'POST',
      path: '/<%= pluralName %>',
      config: {
        description: 'Creates a <%= name %>',
        notes: 'Creates a <%= name %>',
        tags: ['api', 'create'],
        handler: <%= controllerName %>.create,
        plugins: {
          'hapi-swagger': {
              responses: {
                  '201': {
                      'description': 'Created'
                  },
                  '400': {
                      'description': 'Bad Request'
                  }
              }
          }
        },
        validate: {
          payload: {
            // TODO: Add some validations
          }
        }
      }
    },
		
    {
      method: 'GET',
      path: '/<%= pluralName %>',
      config : {
        description: 'Fetches all <%= pluralName %>',
        handler: <%= controllerName %>.find,
        notes: 'Fetches all <%= pluralName %>',
        tags: ['api', 'query'],
        plugins: {
          'hapi-swagger': {
            responses: {
              '200': {
                  'description': 'Success'
              },
              '400': {
                  'description': 'Bad Request'
              },
              '405': {
                  'description': 'Method Not Allowed'
              }
            }
          }
        },
        validate: {
          // TODO: Add some validations
        }
      }
    },
		
    {
      method: 'GET',
      path: '/<%= pluralName %>/{id}',
      config : {
        description: 'Fetches a <%= name %> by id',
        handler: <%= controllerName %>.findById,
        notes: 'Fetches a <%= name %> by id',
        tags: ['api', 'query'],
        plugins: {
          'hapi-swagger': {
              responses: {
                  '200': {
                      'description': 'Success'
                  },
                  '400': {
                      'description': 'Bad Request'
                  }
              }
          }
        },
        validate: {
          params: {
            id: Joi.number().integer().required()
          }
        }
      }
    },
		
    {
      method: 'PUT',
      path: '/<%= pluralName %>/{id}',
      config : {
        description: 'Updates a <%= name %> for a specific id',
        handler: <%= controllerName %>.update,
        notes: 'Updates a <%= name %> for a specific id',
        tags: ['api', 'update'],
        plugins: {
            'hapi-swagger': {
                responses: {
                    '200': {
                        'description': 'Success'
                    },
                    '400': {
                        'description': 'Bad Request'
                    }
                }
            }
        },
        validate: {
          params: {
            id: Joi.number().integer().required()
          },
          payload: {
            // TODO: Add some validations
          }
        }
      }
    },
		
    {
      method: 'DELETE',
      path: '/<%= pluralName %>/{id}',
      config : {
        description: 'Remove a <%= name %> for a specific id',
        handler: <%= controllerName %>.remove,
        notes: 'BACKOFFICE ONLY - Permit to delete a parent object by its identifier',
        tags: ['api', 'delete'],
        plugins: {
          'hapi-swagger': {
              responses: {
                  '204': {
                      'description': 'No Content'
                  },
                  '405': {
                      'description': 'Method Not Allowed'
                  }
              }
          }
        },
        validate: {
          params: {
            id: Joi.number().integer().required()
          }
        }
      }
    }
		
		/* Add new methods above */
  ]
}();
