// This is a file generated by the yeoman generator hapijs

/**
 * Model layer which actually gets <%= name %> from the datastore
 *
 * @type {exports}
 */
'use strict';

const Boom = require('boom');
const Model = require('objection').Model;

class <%= modelName %> extends Model {
    static get tableName() {
        return '<%= modelName %>';
    }
}

module.exports = <%= modelName %>;
